name = "highlow"
kind = "light"

[hues]
red = 15.0
orange = 62.0
yellow = 98.0
green = 135.0
cyan = 223.0
blue = 262.0
purple = 314.0
pink = 346.0

[groups.fg]
lightness = 0.36
chroma = 0.07

[groups.fg_accented]
lightness = 0.36
chroma = 0.10

[groups.fg_unaccented]
lightness = 0.36
chroma = 0.05

[groups.bg]
lightness = 0.85
chroma = 0.05

[colors]
bg = [0.95, 0.016, 77]
fg = [0.36, 0.035, 272]
grey = [0.36, 0.0, 77]

[themes.ui]
fg = "fg"
fg_dim = { color = "fg", mix = ["bg", 0.1] }
fg_very_dim = { color = "fg", mix = ["bg", 0.3] }
bg = "bg"
bg_visual = { color = "bg", lighten_absolute = -0.15, saturate = 0.04 }
bg_highlight = { color = "bg", lighten_absolute = -0.15, saturate = 0.03 }
bg_highlight_dim = { color = "bg", lighten_absolute = -0.07, saturate = 0.02 }
bg_border = { color = "fg" }
bg_gutter = { color = "bg", lighten_absolute = -0.04, saturate = 0.015 }
bg_dim = { color = "bg", lighten_absolute = -0.05, saturate = -0.005 }
bg_selected = { color = "bg", lighten_absolute = -0.1 }
float_bg = { color = "bg", lighten_absolute = -0.02, saturate = 0.01 }
float_fg = { color = "fg", lighten_absolute = -0.02 }
float_border = "fg"
pmenu_bg = { color = "bg", lighten_absolute = -0.1, saturate = 0.03 }
pmenu_fg = { color = "fg", lighten_absolute = -0.1 }
pmenu_fg_selected = { color = "fg", lighten_absolute = -0.1, saturate = 0.03 }
pmenu_bg_selected = { color = "bg", lighten_absolute = -0.25, saturate = 0.08 }
special = { color = "fg.purple", lighten_absolute = -0.05, saturate = 0.02 }
nontext = { color = "grey", mix = ["bg", 0.15] }

[themes.syn]
string = "fg.green"
number = "fg.orange"
constant = "fg.blue"
regex = "fg.yellow"
preproc = "fg.yellow"
type = "fg.pink"
variable = "fg"
identifier = "fg"
parameter = "fg_unaccented.blue"
function = "fg_unaccented.blue"
constructor = "fg_unaccented.orange"
statement = "fg_unaccented.purple"
keyword = "fg_unaccented.purple"
operator = "fg_unaccented.yellow"
deprecated = { color = "grey", lighten_absolute = 0.05 }
comment = "grey"
special = "fg.yellow"
punctuation = { color = "grey", lighten_absolute = 0.05 }

[themes.diagnostics]
error = { color = "fg_accented.red" }
warning = { color = "fg_accented.orange" }
info = { color = "fg_accented.blue" }
hint = { color = "fg_accented.blue", saturate = -0.05 }
ok = { color = "fg_accented.green" }

[themes.vcs]
removed = "fg.red"
added = "fg.green"
changed = "fg.yellow"

[themes.diff]
removed = "bg.red"
added = "bg.green"
changed = "bg.yellow"
text = "bg"

[inverse]
saturate = -0.03
lighten_absolute = 0.08

[highlights]
StatusLine = { fg = "ui.bg", bg = "ui.fg" }
StatusLineNC = { fg = "ui.bg_dim", bg = "ui.fg_very_dim" }
